# Generated by Django 3.2.5 on 2021-07-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nombre_cat', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nombre_pro', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cantidad_pro', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_pro', models.FloatField(verbose_name='Precio')),
                ('imagen_pro', models.ImageField(blank=True, null=True, upload_to='Imagenes/%Y/%m/%d', verbose_name='Imagen')),
                ('fk_id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmaSaludApp.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
