# Generated by Django 3.2.5 on 2021-07-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmaSaludApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fk_id_cat',
            new_name='fk_idcat',
        ),
    ]
