# Generated by Django 3.2.5 on 2021-07-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmaSaludApp', '0003_rename_fk_idcat_producto_fk_id_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_pro',
            field=models.CharField(max_length=100, null=True, verbose_name='Imagen'),
        ),
    ]
